### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by mubix** [lunarca/pyemailprotectionslib#7]
If fixed the initial issues via #1 
but now I get:
```
root@kali:/opt/spoofcheck# ./spoofcheck.py cyberotic.io
Traceback (most recent call last):
  File "./spoofcheck.py", line 11, in <module>
    from libs.PrettyOutput import output_good, output_bad, \
  File "/opt/spoofcheck/libs/PrettyOutput.py", line 5
    print Fore.GREEN + Style.BRIGHT + "[+]" + Style.RESET_ALL, line
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(Fore.GREEN + Style.BRIGHT + "[+]" + Style.RESET_ALL, line)?
```

**Comment by mubix** [comment]
Sorry, this isn't a problem with this project but with https://github.com/BishopFox/spoofcheck
